Repository WavetexDev/wds-core, pull requests merged in 2023-08, with the labels that each got.

#23 refactor: changed the isColorDark function to use polished
  src/utils/check-color-brigthness.ts
Labels: enhancement

#24 Refactor/school colors
  index.d.ts
  src/components/Avatar/styles.ts
  src/components/buttons/floating/styles.ts
  src/components/buttons/regular/styles.ts
  src/components/lecture-card/styles.ts
  src/components/module-card/styles.ts
  src/components/pill/styles.ts
  src/components/progress-bar/styles.ts
  src/components/story-circle/styles.ts
  src/theme.ts
  src/utils/get-school-colors.ts
Labels: enhancement

#25 Refactor: lecture card duration display
  src/components/lecture-card/index.tsx
  src/components/lecture-card/types.ts
Labels: enhancement

#29 fix: updated type declaration
  index.d.ts
Labels: bug

#31 fix: styled-components import
  src/components/buttons/filter/index.tsx
  src/components/buttons/floating/index.tsx
  src/components/buttons/option/index.tsx
  src/components/buttons/regular/index.tsx
  src/components/course-banner/index.tsx
  src/components/grid-item/index.tsx
  src/components/inputs/input/index.tsx
  src/components/inputs/search/index.tsx
  src/components/lecture-card/index.tsx
  src/components/module-card/index.tsx
  src/components/number-badge/index.tsx
  src/components/pill/index.tsx
  src/components/progress-bar/index.tsx
  src/components/story-circle/index.tsx
  src/components/typography/index.tsx
Labels: bug

#34 feat: Card and Paper components with stories
  src/components/card/index.tsx
  src/components/card/styles.ts
  src/components/card/types.ts
  src/components/module-card/types.ts
  src/components/paper/index.tsx
  src/components/paper/styles.ts
  src/components/paper/types.ts
  stories/docs/card/card.stories.tsx
  stories/docs/paper/paper.stories.tsx
Labels: enhancement

#32 Update Github README.md
  README.md
Labels: documentation

#28 feat: NotificationCard component
  src/components/notification-card/index.tsx
  src/components/notification-card/types.ts
  src/utils/format-date.ts
  stories/notification-card/notification-card.stories.tsx
Labels: enhancement
